---
deployment:
  tasks:
    - export DEPLOYPATH=/home/m197082/freakfestival.es/
    - /bin/cp charlas.php $DEPLOYPATH
    - /bin/cp colaboradores.php $DEPLOYPATH
    - /bin/cp concursos.php $DEPLOYPATH
    - /bin/cp edicion-2018.php $DEPLOYPATH
    - /bin/cp edicion-2022.php $DEPLOYPATH
    - /bin/cp edicion-2023.php $DEPLOYPATH
    - /bin/cp horario.php $DEPLOYPATH
    - /bin/cp index.php $DEPLOYPATH
    - /bin/cp inscripciones-candidaturas.php $DEPLOYPATH
    - /bin/cp invitados.php $DEPLOYPATH
    - /bin/cp juegos-de-mesa.php $DEPLOYPATH
    - /bin/cp mapas-recinto.php $DEPLOYPATH
    - /bin/cp organizadores.php $DEPLOYPATH
    - /bin/cp presentaciones-de-libros.php $DEPLOYPATH
    - /bin/cp rol-de-mesa.php $DEPLOYPATH
    - /bin/cp rol-en-vivo.php $DEPLOYPATH
    - /bin/cp talleres.php $DEPLOYPATH
    - /bin/cp torneos.php $DEPLOYPATH
    - /bin/cp -R docs $DEPLOYPATH
    - /bin/cp -R eu $DEPLOYPATH
    # - /bin/cp -R fonts $DEPLOYPATH
    - /bin/cp -R images $DEPLOYPATH
    - /bin/cp -R include $DEPLOYPATH
    # - /bin/cp -R js $DEPLOYPATH
    - /bin/cp -R lang $DEPLOYPATH
    - /bin/cp -R libraries $DEPLOYPATH
    - /bin/cp -R styles $DEPLOYPATH