---
deployment:
  tasks:
    - export DEPLOYPATH=/home/m197082/freakfestival.es/
    - /bin/cp actividades.php $DEPLOYPATH
    - /bin/cp colaboradores.php $DEPLOYPATH
    - /bin/cp concursos.php $DEPLOYPATH
    - /bin/cp donde-alojarse.php $DEPLOYPATH
    - /bin/cp fotos.php $DEPLOYPATH
    - /bin/cp horario-de-actividades.php $DEPLOYPATH
    - /bin/cp index.php $DEPLOYPATH
    - /bin/cp inscripciones-candidaturas.php $DEPLOYPATH
    - /bin/cp invitados.php $DEPLOYPATH
    - /bin/cp salas.php $DEPLOYPATH
    - /bin/cp organizadores.php $DEPLOYPATH
    - /bin/cp puestos.php $DEPLOYPATH
    - /bin/cp -R docs $DEPLOYPATH
    - /bin/cp -R eu $DEPLOYPATH
    # - /bin/cp -R fonts $DEPLOYPATH
    - /bin/cp -R images $DEPLOYPATH
    - /bin/cp -R include $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp -R lang $DEPLOYPATH
    - /bin/cp -R libraries $DEPLOYPATH
    - /bin/cp -R styles $DEPLOYPATH