<?php
$links = array(
  "es.index" => "index",
  "es.actividades" => "actividades",
  "es.horario-de-actividades" => "horario-de-actividades",
  "es.salas" => "salas",
  "es.inscripciones-candidaturas" => "inscripciones-candidaturas",
  "es.concursos" => "concursos",
  "es.puestos" => "puestos",
  "es.invitados" => "invitados",
  "es.donde-dormir" => "donde-dormir",
  "es.organizadores" => "organizadores",
  "es.colaboradores" => "colaboradores",
  "es.edicion-2024" => "edicion-2024",
  "es.edicion-2023" => "edicion-2023",
  "es.edicion-2022" => "edicion-2022",
  "es.edicion-2018" => "edicion-2018",

  "eu.index" => "index",
  "eu.actividades" => "jarduerak",
  "eu.horario-de-actividades" => "jardueren-ordutegia",
  "eu.salas" => "aretoak",
  "eu.inscripciones-candidaturas" => "izen-emateak-hautagaitzak",
  "eu.concursos" => "lehiaketak",
  "eu.puestos" => "postuak",
  "eu.invitados" => "gonbidatuak",
  "eu.donde-dormir" => "non-lo-egin",
  "eu.organizadores" => "antolatzaileak",
  "eu.colaboradores" => "laguntzaileak",
  "eu.edicion-2024" => "2024-edizioa",
  "eu.edicion-2023" => "2023-edizioa",
  "eu.edicion-2022" => "2022-edizioa",
  "eu.edicion-2018" => "2018-edizioa",
);
?>