<?php
$links = [
  "es.index" => "/index",
  "es.activities" => "/actividades",
  "es.timetable" => "/horario-de-actividades",
  "es.maps" => "/planos",
  "es.registrations-applications" => "/inscripciones-candidaturas",
  "es.contests" => "/concursos",
  "es.stands" => "/puestos",
  "es.guests" => "/invitados",
  "es.organizers" => "/organizadores",
  "es.contributors" => "/colaboradores",
  "es.photos" => "/fotos",
  "es.posters" => "/carteles",

  "eu.index" => "/eu/index",
  "eu.activities" => "/eu/jarduerak",
  "eu.timetable" => "/eu/jardueren-ordutegia",
  "eu.maps" => "/eu/planoak",
  "eu.registrations-applications" => "/eu/izen-emateak-hautagaitzak",
  "eu.contests" => "/eu/lehiaketak",
  "eu.stands" => "/eu/postuak",
  "eu.guests" => "/eu/gonbidatuak",
  "eu.organizers" => "/eu/antolatzaileak",
  "eu.contributors" => "/eu/laguntzaileak",
  "eu.photos" => "/eu/argazkiak",
  "eu.posters" => "/eu/kartelak",
];
