<?php
$links = array(
  "es.index" => "index",
  "es.horario-de-actividades" => "horario-de-actividades",
  "es.salas" => "salas",
  "es.juegos-de-mesa" => "juegos-de-mesa",
  "es.torneos" => "torneos",
  "es.rol-de-mesa" => "rol-de-mesa",
  "es.rol-en-vivo" => "rol-en-vivo",
  "es.charlas" => "charlas",
  "es.presentaciones-de-libros" => "presentaciones-de-libros",
  "es.talleres" => "talleres",
  "es.otras-actividades" => "otras-actividades",
  "es.inscripciones-candidaturas" => "inscripciones-candidaturas",
  "es.concursos" => "concursos",
  "es.puestos" => "puestos",
  "es.invitados" => "invitados",
  "es.donde-dormir" => "donde-dormir",
  "es.organizadores" => "organizadores",
  "es.colaboradores" => "colaboradores",
  "es.edicion-2023" => "edicion-2023",
  "es.edicion-2022" => "edicion-2022",
  "es.edicion-2018" => "edicion-2018",

  "eu.index" => "index",
  "eu.horario-de-actividades" => "jardueren-ordutegia",
  "eu.salas" => "aretoak",
  "eu.juegos-de-mesa" => "mahai-jokoak",
  "eu.torneos" => "txapelketak",
  "eu.rol-de-mesa" => "mahaiko-rola",
  "eu.rol-en-vivo" => "zuzeneko-rola",
  "eu.charlas" => "hitzaldiak",
  "eu.presentaciones-de-libros" => "liburu-aurkezpenak",
  "eu.talleres" => "tailerrak",
  "eu.otras-actividades" => "beste-jarduerak",
  "eu.inscripciones-candidaturas" => "izen-emateak-hautagaitzak",
  "eu.concursos" => "lehiaketak",
  "eu.puestos" => "postuak",
  "eu.invitados" => "gonbidatuak",
  "eu.donde-dormir" => "non-lo-egin",
  "eu.organizadores" => "antolatzaileak",
  "eu.colaboradores" => "laguntzaileak",
  "eu.edicion-2023" => "2023-edizioa",
  "eu.edicion-2022" => "2022-edizioa",
  "eu.edicion-2018" => "2018-edizioa",
);
?>